import type { WorkspaceLanguage } from '../shared/types.js'

export const clarificationRouting = (language: WorkspaceLanguage = 'zh') =>
  language === 'en'
    ? 'For grill/grilling/grill-me/grill-with-docs requests, delegate BEFORE reading the interview instructions or asking questions: identify the available interview skill with team skill list, then run team grill "<requirements brief>" --skill "<pack/grill-skill>". HiveTeam reuses an idle suitable member or creates a dedicated interviewer using the Orchestrator preset/model; general dynamic staffing need not be enabled. Busy work, temporary-member limits and execution authorization remain enforced. Keep the printed request_id; retry the same brief and skill with --request-id <id> to avoid duplicate members or dispatches. On HTTP 401/403, a transport error or ok:false, stop and report the failure; do not treat it as an empty team or conduct the interview here. After a confirmed handoff, tell the user the returned member name and which member window to answer in. A queued status means the task is saved and awaiting startup/delivery; do not claim the member has received it. Do not use native subagents. Await only the final team report, then decompose and dispatch implementation tasks. Do not read interview notes or request intermediate answers/status.'
    : '收到 grill/grilling/grill-me/grill-with-docs 请求时，必须先转交，不要在主线程读取访谈 Skill 正文或提问：用 team skill list 确认可用访谈 Skill，再执行 team grill "<需求简述>" --skill "<pack/grill-skill>"。HiveTeam 复用合适的空闲成员，无可用成员时沿用主控的 CLI 预设和模型创建专用需求访谈员，无需开启通用动态增员；不打断忙碌任务，临时成员上限和执行授权仍生效。保留命令打印的 request_id，重试同一简述和 Skill 时使用 --request-id <id>，避免重复建成员或派单。遇到 HTTP 401/403、网络错误或 ok:false 时停止并报告故障，不得当作空团队，也不得改在主线程自行访谈。交接成功后告诉用户返回的成员名称及应进入的成员窗口；status=queued 仅表示任务已保存、等待启动或投递，不得宣称成员已收到。不用内置 subagent。主线程只等待最终 team report，再拆解和派发实现任务；不读取访谈记录，不索要中间问答或状态正文。'

export const workerClarificationGuidance = (dispatchId: string, language: WorkspaceLanguage) => {
  const folder = `docs/clarifications/${dispatchId}`
  return language === 'en'
    ? `HiveTeam clarification contract: conduct this interview entirely in YOUR member window. Accept free-form answers and edits, not just numbered options. Wait for the user there; waiting for an answer is not a blocked outcome and must not trigger team report. Keep interview notes in ${folder}/interview.md, not shared tasks/context/memory. Present the final plan in your window and ${folder}/final.md for explicit user confirmation. Only after confirmation, report once with team report --stdin --dispatch ${dispatchId} --outcome success: a concise summary (at most 6000 characters) of goals, scope, decisions, constraints, acceptance criteria, risks, and the final document path. Never include the Q&A transcript or intermediate drafts. Do not implement or dispatch tasks; the Orchestrator handles that after your final handoff. If genuinely unable to continue, report only the terminal outcome and concise reason, without the interview history. If cancelled, follow the HiveTeam cancellation protocol; do not report on a cancelled dispatch.`
    : `HiveTeam 需求澄清合同：完整访谈只在你自己的成员窗口进行。支持用户自由填写和修改答案，不限定编号选项。提问后在本窗口等待用户；等待回答不是阻塞，不要因此 team report。访谈记录写入 ${folder}/interview.md，不写共享 tasks、CONTEXT 或 memory。最终方案在本窗口展示并写入 ${folder}/final.md，等待用户明确确认。确认后才使用 team report --stdin --dispatch ${dispatchId} --outcome success 回传一次精简结论（最多 6000 字符）：目标、范围、决策、约束、验收标准、风险及最终文档路径。不回传逐轮问答和中间草稿。不实现、不派工，由 Orchestrator 收到最终结论后拆解和分派。真正无法继续时仅汇报终止结果和简短原因，不附访谈历史；取消后遵循 HiveTeam 取消协议。`
}
