export interface CodexExecutionProfileInput {
  workspacePath: string
  cliHome: string
  scratchPath: string
  mailboxPath: string
  executableRoots: string[]
  gitReadRoots: string[]
  denyPaths: string[]
  sourceWritable: boolean
  toolPath: string
  hiveEnv: Record<string, string>
}

/** This file is generated by the trusted runtime outside every writable checkout. */
export const buildCodexExecutionProfile = (input: CodexExecutionProfileInput) => {
  const filesystem = new Map<string, 'read' | 'write' | 'deny'>([
    [':root', 'deny'],
    [':minimal', 'read'],
    [input.workspacePath, input.sourceWritable ? 'write' : 'read'],
    [input.scratchPath, 'write'],
    [input.mailboxPath, 'read'],
    [`${input.mailboxPath}/requests`, 'write'],
    [`${input.mailboxPath}/responses`, 'read'],
    ...input.executableRoots.map((root): [string, 'read'] => [root, 'read']),
    ...input.gitReadRoots.map((root): [string, 'read'] => [root, 'read']),
    ...input.denyPaths.map((path): [string, 'deny'] => [path, 'deny']),
  ])
  const lines = [
    'model = "gpt-5.4"',
    'default_permissions = "hive_restricted"',
    'approval_policy = "never"',
    'web_search = "disabled"',
    'cli_auth_credentials_store = "file"',
    `[projects.${JSON.stringify(input.workspacePath)}]`,
    'trust_level = "untrusted"',
    '[features]',
    ...[
      'apps',
      'browser_use',
      'browser_use_external',
      'computer_use',
      'plugins',
      'remote_plugin',
      'hooks',
      'view_image',
      'multi_agent',
      'goals',
      'shell_snapshot',
      'skill_mcp_dependency_install',
    ].map((feature) => `${feature} = false`),
    '[permissions.hive_restricted.filesystem]',
    ...[...filesystem].map(
      ([path, access]) => `${JSON.stringify(path)} = ${JSON.stringify(access)}`
    ),
    '[permissions.hive_restricted.network]',
    'enabled = false',
    '[shell_environment_policy]',
    'inherit = "none"',
    'experimental_use_profile = false',
    '[shell_environment_policy.set]',
    ...Object.entries({
      PATH: input.toolPath,
      HOME: input.scratchPath,
      TMPDIR: input.scratchPath,
      LANG: 'C.UTF-8',
      ...input.hiveEnv,
    }).map(([name, value]) => `${JSON.stringify(name)} = ${JSON.stringify(value)}`),
  ]
  return `${lines.join('\n')}\n`
}
