import { useI18n } from '../i18n.js'

const en = {
  answer: 'Your reply',
  replyTo: 'Reply to',
  memberOnly: 'Sent only to this member, not to Orchestrator.',
  clarification:
    'Requirement clarification stays in the member window. Orchestrator waits for the final report.',
  openInterview: 'Answer in member window',
  interview: 'Requirement clarification',
  question: 'Question or earlier answer to revise (optional)',
  answerHint: 'Write in your own words. Enter adds a line; Ctrl/⌘ + Enter sends.',
  placeholder: 'None of those options? Describe what you need…',
  send: 'Send reply',
  plans: 'Plan documents',
  close: 'Close plan documents',
  title: 'Review the plan',
  description:
    'Read the source, edit a separate draft, and ask Orchestrator to review your changes.',
  document: 'Document',
  empty: 'No Markdown documents yet. Ask Orchestrator to save a plan in docs/.',
  loading: 'Loading documents…',
  refresh: 'Reload source',
  limited: 'List limited to 1,500 entries and six folder levels.',
  preview: 'Preview',
  edit: 'Edit draft',
  changes: 'Changes',
  source: 'Source file',
  draft: 'Your draft',
  draftHint:
    'Drafts are stored in Hive. Saving does not overwrite the project file or contact the model.',
  note: 'Instructions for this revision (optional)',
  save: 'Save draft',
  review: 'Send changes for review',
  confirm: 'Confirm source version',
  confirmed: 'This source version is confirmed. Implementation has not been started.',
  unconfirmed: 'Source version not confirmed',
  changed: 'The source changed after this draft was created. Your draft is retained.',
  sourceAction: 'Replace draft with latest source',
  conflictHelp: 'Reload to inspect the latest source. Copy your edits before replacing the draft.',
  dirty: 'Unsaved draft',
  saved: 'Draft saved — not sent',
  savedDraft: 'Draft saved',
  noDiff: 'No text changes. You can add review instructions below.',
  reviewHint:
    'Review only: Orchestrator should revise the plan and wait for confirmation, not implement it.',
  blocked: 'Not sent. Start the recipient or wait for the previous submission, then retry.',
  sending: 'Waiting for terminal submission… Do not resend in the terminal.',
  submitted: 'Submitted to the terminal. Check the model’s reply; this is not a review approval.',
  uncertain:
    'Delivery is uncertain. Check the terminal before sending again; Hive will not retry automatically.',
  sendingButton: 'Submitting…',
  unresolved: 'Submission has not been verified. Check its status before resending.',
  retryStatus: 'Check submission status',
  storageError:
    'Browser draft storage is unavailable. Keep this panel open and save your draft to Hive.',
  closeDirty: 'Keep editing',
  discard: 'Close without keeping browser draft',
  sourceMismatch:
    'Confirmation applies to the source file only. First ask the model to incorporate your draft, then reload.',
  confirmHint:
    'Records this exact source version in Hive. Does not start implementation or send a command.',
  latestSource: 'Latest source (your draft has not been replaced)',
  networkError:
    'Could not read submission status. Your content is retained; check status before resending.',
}
const zh: typeof en = {
  answer: '自由回答',
  replyTo: '回答给',
  memberOnly: '仅发送给这位成员，不转发给 Orchestrator。',
  clarification: '需求澄清在成员窗口进行，Orchestrator 等待最终结论。',
  openInterview: '进入成员窗口回答',
  interview: '需求澄清',
  question: '对应问题／要修改的旧答案（可选）',
  answerHint: '直接表达你的想法。Enter 换行；Ctrl/⌘ + Enter 发送。',
  placeholder: '不必局限于选项，填写你的完整回答…',
  send: '发送回答',
  plans: '方案文档',
  close: '关闭方案文档',
  title: '方案评审',
  description: '查看项目原文，编辑独立草稿，再把修改交给 Orchestrator 复核。',
  document: '文档',
  empty: '暂未发现 Markdown 文档。可以让 Orchestrator 把方案保存到 docs/ 目录。',
  loading: '正在读取文档…',
  refresh: '重新读取原文',
  limited: '列表最多扫描 1,500 个条目、六层目录。',
  preview: '预览',
  edit: '编辑草稿',
  changes: '修改差异',
  source: '项目原文',
  draft: '我的草稿',
  draftHint: '草稿单独保存在 Hive。保存不会覆盖项目文件，也不会发送给模型。',
  note: '本次修改说明（可选）',
  save: '保存草稿',
  review: '发送修改供复核',
  confirm: '确认原文此版本',
  confirmed: '原文此版本已确认；尚未启动实现。',
  unconfirmed: '原文此版本尚未确认',
  changed: '项目原文在你编辑后发生了变化，你的草稿已保留。',
  sourceAction: '用最新原文替换草稿',
  conflictHelp: '重新读取以检查最新原文。替换草稿前，请复制保留需要的修改。',
  dirty: '草稿尚未保存',
  saved: '草稿已保存，尚未发送',
  savedDraft: '草稿已保存',
  noDiff: '正文没有变化，也可以在下方补充复核意见。',
  reviewHint: '仅复核方案：要求 Orchestrator 修订并等待再次确认，不开始实现。',
  blocked: '尚未发送。请启动接收成员，或等待上一条提交完成后重试。',
  sending: '正在等待终端接收…请勿在终端重复发送。',
  submitted: '已提交到终端，请查看模型回复；这不代表方案已通过复核。',
  uncertain: '发送结果不确定。请先查看终端确认；Hive 不会自动重发。',
  sendingButton: '提交中…',
  unresolved: '尚未核实提交结果。请先检查状态，不要重复发送。',
  retryStatus: '检查提交状态',
  storageError: '浏览器无法保留草稿。请勿关闭面板，并将草稿保存到 Hive。',
  closeDirty: '继续编辑',
  discard: '关闭且不保留浏览器草稿',
  sourceMismatch: '只能确认项目原文。请先让模型采纳草稿修改，再重新读取原文确认。',
  confirmHint: '只在 Hive 记录原文此版本的确认，不开始实现，也不发送命令。',
  latestSource: '最新原文（尚未替换你的草稿）',
  networkError: '无法查询提交状态。内容已保留，请先检查状态，不要重复发送。',
}
export const useReviewCopy = () => (useI18n().language === 'zh' ? zh : en)
